defaults: &defaults
  resource_class: small
  docker:
    - image: cimg/node:20.9.0
cache-npm: &cache-npm
  keys:
    - -{{ checksum "package-lock.json" }}
cache-build: &cache-build
  keys:
    - -build_{{ .Revision }}

orbs:
  cypress: cypress-io/cypress@3

parameters:
  skip-coveralls:
    type: boolean
    default: false
  skip-security:
    type: boolean
    default: false
  skip-leaks:
    type: boolean
    default: false
  skip-deploy:
    type: boolean
    default: false

aliases:
  - &set-github-read-token
    name: Set Danger Token
    command: |
            echo 'export DANGER_GITHUB_API_TOKEN=$(echo Z2hwXzFldFVxODNZTUhCa0ZQUjk0WVV1blFXZTFCVmkzajRSOEpxRQo= | base64 --decode)' >> $BASH_ENV
            source $BASH_ENV
  - &danger-pr
    name: Run danger
    command: npx danger ci -d .dangerfile.js
  - &build
    name: Build
    command: npx netlify build
  - &install
    name: Installing Dependencies
    command: npm ci
  - &cache-modules
    key: -{{ checksum "package-lock.json" }}
    paths:
      - ~/.npm
      - node_modules
      - src/locales
  - &cache-build
    key: -build_{{ .Revision }}
    paths:
      - dist
      - .netlify

version: 2.1
debug: true
jobs:
  danger-pr:
    <<: *defaults
    steps:
      - checkout
      - run: *install
      - run: *set-github-read-token
      - run: *danger-pr
      
  install:
    docker:
      - image: cimg/node:20.9.0
    resource_class: medium
    steps:
      - checkout
      - run: *install
      - run: *build
      - run: *danger-pr
      - run:
          name: Send to staging
          command: "npx netlify deploy --alias staging"
      - save_cache: *cache-modules
      - save_cache: *cache-build
  test-lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          <<: *cache-npm
      - run:
          name: Run Lint
          command: "npm run test:lint"
  test-cypress:
    resource_class: medium
    docker:
      - image: cypress/browsers:node-20.11.0-chrome-121.0.6167.85-1-ff-120.0-edge-121.0.2277.83-1
    steps:
      - checkout
      - restore_cache:
          <<: *cache-npm
      - run:
          name: Print machine info
          command: npx cypress info
      - cypress/install:
          package-manager: npm
      - cypress/run-tests:
          cypress-command: npm run test:unit
      - cypress/run-tests:
          cypress-command: npm run test:e2e
      - store_artifacts:
          path: reports
  test-leaks:
    resource_class: small
    docker:
      - image: zricethezav/gitleaks:v7.6.1
    steps:
      - checkout
      - when:
          condition:
            not: << pipeline.parameters.skip-leaks >>
          steps:
            - run:
                name: Run gitleaks
                command: "gitleaks -v --path . --config-path .gitleaks.toml"
  deploy:
    <<: *defaults
    steps:
      - checkout
      - when:
          condition:
            not: << pipeline.parameters.skip-deploy >>
          steps:
            - restore_cache:
                <<: *cache-npm     
            - restore_cache:
                <<: *cache-build
            - run:
                name: Create Release
                command: if [ -z ${CIRCLE_SKIP_DEPLOY+x} ]; then npm run semantic-release;else echo 'job skipped';fi

workflows:
  version: 2
  main:
    jobs:
      - install:
          context: branches
      - test-leaks:
          requires:
            - install
      - test-lint:
          requires:
            - install
      - test-cypress:
          requires:
            - install
      - deploy:
          requires:
            - install
            - test-lint
            - test-cypress
          context: npm-packages
          filters:
            branches:
                only: master
  pr:
    jobs:
      - danger-pr:
          filters:
            branches:
              only: /pull\/[0-9]+/
